# TCL File Generated by Component Editor 8.0 
# Tue Jul 29 11:22:51 BST 2008 
# DO NOT MODIFY 
 
 
# +----------------------------------- 
# |  
# | opencores_i2c_master "OpenCores I2C Master" v2.1 
# | null 2008.07.29.11:22:51 
# |  
# |  
# | oc_i2c_master.vhd 
# |  
# |    ./i2c_master_bit_ctrl.vhd syn, sim 
# |    ./i2c_master_byte_ctrl.vhd syn, sim 
# |    ./i2c_master_top.vhd syn, sim 
# |    ./oc_i2c_master.vhd syn, sim 
# |  
# +----------------------------------- 
 
 
# +----------------------------------- 
# | module opencores_i2c_master 
# |  
set_module_property NAME opencores_i2c_master 
set_module_property VERSION 2.1.1 
set_module_property GROUP Communication 
set_module_property DISPLAY_NAME "OpenCores I2C Master" 
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.std_logic_arith.all std.standard.all} 
set_module_property TOP_LEVEL_HDL_FILE hdl/oc_i2c_master.vhd 
set_module_property TOP_LEVEL_HDL_MODULE oc_i2c_master 
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true 
set_module_property EDITABLE false 
set_module_property SIMULATION_MODEL_IN_VERILOG false 
set_module_property SIMULATION_MODEL_IN_VHDL false 
set_module_property SIMULATION_MODEL_HAS_TULIPS false 
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false 
# |  
# +----------------------------------- 
 
# +----------------------------------- 
# | files 
# |  
add_file hdl/oc_i2c_master_bit_ctrl.vhd {SYNTHESIS SIMULATION} 
add_file hdl/oc_i2c_master_byte_ctrl.vhd {SYNTHESIS SIMULATION} 
add_file hdl/oc_i2c_master_top.vhd {SYNTHESIS SIMULATION} 
add_file hdl/oc_i2c_master.vhd {SYNTHESIS SIMULATION} 
# |  
# +----------------------------------- 
 
# +----------------------------------- 
# | parameters 
# |  
# |  
# +----------------------------------- 
 
# +----------------------------------- 
# | connection point s1_clk 
# |  
add_interface s1_clk clock end 
set_interface_property s1_clk ptfSchematicName "" 
 
add_interface_port s1_clk wb_clk_i clk Input 1 
add_interface_port s1_clk arst_i_n reset_n Input 1 
# |  
# +----------------------------------- 
 
# +----------------------------------- 
# | connection point s1 
# |  
add_interface s1 avalon end 
set_interface_property s1 holdTime 0 
set_interface_property s1 linewrapBursts false 
set_interface_property s1 minimumUninterruptedRunLength 1 
set_interface_property s1 bridgesToMaster "" 
set_interface_property s1 isMemoryDevice false 
set_interface_property s1 burstOnBurstBoundariesOnly false 
set_interface_property s1 addressSpan 32 
set_interface_property s1 timingUnits Cycles 
set_interface_property s1 setupTime 0 
set_interface_property s1 writeWaitTime 0 
set_interface_property s1 isNonVolatileStorage false 
set_interface_property s1 addressAlignment DYNAMIC 
set_interface_property s1 maximumPendingReadTransactions 0 
set_interface_property s1 readWaitTime 1 
set_interface_property s1 readLatency 0 
set_interface_property s1 printableDevice false 
 
set_interface_property s1 ASSOCIATED_CLOCK s1_clk 
 
add_interface_port s1 wb_ack_o waitrequest_n Output 1 
add_interface_port s1 wb_adr_i address Input 3 
add_interface_port s1 wb_dat_i writedata Input 32 
add_interface_port s1 wb_dat_o readdata Output 32 
add_interface_port s1 wb_stb_i chipselect Input 1 
add_interface_port s1 wb_we_i write Input 1 
# |  
# +----------------------------------- 
 
# +----------------------------------- 
# | connection point global 
# |  
add_interface global conduit end 
 
set_interface_property global ASSOCIATED_CLOCK s1_clk 
 
add_interface_port global scl_pad_io export Bidir 1 
add_interface_port global sda_pad_io export Bidir 1 
# |  
# +----------------------------------- 
 
# +----------------------------------- 
# | connection point s1_irq 
# |  
add_interface s1_irq interrupt end 
set_interface_property s1_irq associatedAddressablePoint s1 
 
set_interface_property s1_irq ASSOCIATED_CLOCK s1_clk 
 
add_interface_port s1_irq wb_inta_o irq Output 1 
# |  
# +----------------------------------- 
