/******************************************************************************
//by mmh create 2018.5.3
******************************************************************************/

#ifndef __TRIANGLE_DEMODU_REGS_H__
#define __TRIANGLE_DEMODU_REGS_H__

#include <io.h>

#define TRIANGLE_DEMODU_AMP_MAX_REG	              	0
#define IOADDR_TRIANGLE_DEMODU_AMP_MAX(base)        	__IO_CALC_ADDRESS_NATIVE(base, TRIANGLE_DEMODU_AMP_MAX_REG)
#define IORD_TRIANGLE_DEMODU_AMP_MAX(base)           IORD(base, TRIANGLE_DEMODU_AMP_MAX_REG) 
#define IOWR_TRIANGLE_DEMODU_AMP_MAX(base, data)     IOWR(base, TRIANGLE_DEMODU_AMP_MAX_REG, data)

#define TRIANGLE_DEMODU_AMP_MIN_REG	              	1
#define IOADDR_TRIANGLE_DEMODU_AMP_MIN(base)        	__IO_CALC_ADDRESS_NATIVE(base, TRIANGLE_DEMODU_AMP_MIN_REG)
#define IORD_TRIANGLE_DEMODU_AMP_MIN(base)           IORD(base, TRIANGLE_DEMODU_AMP_MIN_REG) 
#define IOWR_TRIANGLE_DEMODU_AMP_MIN(base, data)     IOWR(base, TRIANGLE_DEMODU_AMP_MIN_REG, data)

#define TRIANGLE_DEMODU_FREQ_REG	              			2
#define IOADDR_TRIANGLE_DEMODU_FREQ(base)        		__IO_CALC_ADDRESS_NATIVE(base, TRIANGLE_DEMODU_FREQ_REG)
#define IORD_TRIANGLE_DEMODU_FREQ(base)           		IORD(base, TRIANGLE_DEMODU_FREQ_REG) 
#define IOWR_TRIANGLE_DEMODU_FREQ(base, data)     		IOWR(base, TRIANGLE_DEMODU_FREQ_REG, data)

#define TRIANGLE_DEMODU_SAMPLE_POINT_REG	            3
#define IOADDR_TRIANGLE_DEMODU_SAMPLE_POINT(base)    __IO_CALC_ADDRESS_NATIVE(base, TRIANGLE_DEMODU_SAMPLE_POINT_REG)
#define IORD_TRIANGLE_DEMODU_SAMPLE_POINT(base)      IORD(base, TRIANGLE_DEMODU_SAMPLE_POINT_REG) 
#define IOWR_TRIANGLE_DEMODU_SAMPLE_POINT(base, data)    IOWR(base, TRIANGLE_DEMODU_SAMPLE_POINT_REG, data)

#define TRIANGLE_DEMODU_SAMPLE1_START_REG	      				4
#define IOADDR_TRIANGLE_DEMODU_SAMPLE1_START(base) 			__IO_CALC_ADDRESS_NATIVE(base, TRIANGLE_DEMODU_SAMPLE1_START_REG)
#define IORD_TRIANGLE_DEMODU_SAMPLE1_START(base)         IORD(base, TRIANGLE_DEMODU_SAMPLE1_START_REG) 
#define IOWR_TRIANGLE_DEMODU_SAMPLE1_START(base, data)   IOWR(base, TRIANGLE_DEMODU_SAMPLE1_START_REG, data)

#define TRIANGLE_DEMODU_SAMPLE2_START_REG	      				5
#define IOADDR_TRIANGLE_DEMODU_SAMPLE2_START(base) 			__IO_CALC_ADDRESS_NATIVE(base, TRIANGLE_DEMODU_SAMPLE2_START_REG)
#define IORD_TRIANGLE_DEMODU_SAMPLE2_START(base)         IORD(base, TRIANGLE_DEMODU_SAMPLE2_START_REG) 
#define IOWR_TRIANGLE_DEMODU_SAMPLE2_START(base, data)   IOWR(base, TRIANGLE_DEMODU_SAMPLE2_START_REG, data)

#define TRIANGLE_DEMODU_SAMPLE1_NUM_REG	      					6
#define IOADDR_TRIANGLE_DEMODU_SAMPLE1_NUM(base) 				__IO_CALC_ADDRESS_NATIVE(base, TRIANGLE_DEMODU_SAMPLE1_NUM_REG)
#define IORD_TRIANGLE_DEMODU_SAMPLE1_NUM(base)         	IORD(base, TRIANGLE_DEMODU_SAMPLE1_NUM_REG) 
#define IOWR_TRIANGLE_DEMODU_SAMPLE1_NUM(base, data)   	IOWR(base, TRIANGLE_DEMODU_SAMPLE1_NUM_REG, data)

#define TRIANGLE_DEMODU_SAMPLE2_NUM_REG	      					7
#define IOADDR_TRIANGLE_DEMODU_SAMPLE2_NUM(base) 				__IO_CALC_ADDRESS_NATIVE(base, TRIANGLE_DEMODU_SAMPLE2_NUM_REG)
#define IORD_TRIANGLE_DEMODU_SAMPLE2_NUM(base)        		IORD(base, TRIANGLE_DEMODU_SAMPLE2_NUM_REG) 
#define IOWR_TRIANGLE_DEMODU_SAMPLE2_NUM(base, data)   	IOWR(base, TRIANGLE_DEMODU_SAMPLE2_NUM_REG, data)

#endif /*__TRIANGLE_DEMODU_REGS_H__ */
