# TCL File Generated by Component Editor 13.0
# Fri Mar 09 18:36:12 CST 2018
# DO NOT MODIFY


# 
# spi_master "spi master" v1.0
# mmh 2018.03.09.18:36:12
# spi master
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module spi_master
# 
set_module_property DESCRIPTION "spi master"
set_module_property NAME spi_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP System
set_module_property AUTHOR mmh
set_module_property DISPLAY_NAME "spi master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL spi_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file spi_master.v VERILOG PATH hdl/spi_master.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter numberOfSlaves INTEGER 1
set_parameter_property numberOfSlaves DEFAULT_VALUE 1
set_parameter_property numberOfSlaves DISPLAY_NAME numberOfSlaves
set_parameter_property numberOfSlaves TYPE INTEGER
set_parameter_property numberOfSlaves UNITS None
set_parameter_property numberOfSlaves ALLOWED_RANGES -2147483648:2147483647
set_parameter_property numberOfSlaves HDL_PARAMETER true
add_parameter clk_pol INTEGER 0
set_parameter_property clk_pol DEFAULT_VALUE 0
set_parameter_property clk_pol DISPLAY_NAME clk_pol
set_parameter_property clk_pol TYPE INTEGER
set_parameter_property clk_pol UNITS None
set_parameter_property clk_pol ALLOWED_RANGES -2147483648:2147483647
set_parameter_property clk_pol HDL_PARAMETER true
add_parameter clk_pha INTEGER 0
set_parameter_property clk_pha DEFAULT_VALUE 0
set_parameter_property clk_pha DISPLAY_NAME clk_pha
set_parameter_property clk_pha TYPE INTEGER
set_parameter_property clk_pha UNITS None
set_parameter_property clk_pha ALLOWED_RANGES -2147483648:2147483647
set_parameter_property clk_pha HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 54000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end miso export Input 1
add_interface_port conduit_end mosi export Output 1
add_interface_port conduit_end sclk export Output 1
add_interface_port conduit_end ss export Output numberOfSlaves


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 chipselect chipselect Input 1
add_interface_port s1 address address Input 3
add_interface_port s1 read read Input 1
add_interface_port s1 write write Input 1
add_interface_port s1 readdata readdata Output 32
add_interface_port s1 writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt
# 
add_interface interrupt interrupt end
set_interface_property interrupt associatedAddressablePoint s1
set_interface_property interrupt associatedClock clock
set_interface_property interrupt associatedReset reset
set_interface_property interrupt ENABLED true
set_interface_property interrupt EXPORT_OF ""
set_interface_property interrupt PORT_NAME_MAP ""
set_interface_property interrupt SVD_ADDRESS_GROUP ""

add_interface_port interrupt interrupt irq Output 1

