# TCL File Generated by Component Editor 13.0
# Sun Mar 04 21:51:44 CST 2018
# DO NOT MODIFY


# 
# clk_gen "clk_gen" v1.0
# mmh 2018.03.04.21:51:44
# generate clock
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module clk_gen
# 
set_module_property DESCRIPTION "clock generate"
set_module_property NAME clk_gen
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP System
set_module_property AUTHOR mmh
set_module_property DISPLAY_NAME clk_gen
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL clk_gen
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file clk_gen.v VERILOG PATH hdl/clk_gen.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter OSC_CLOCK INTEGER 108000000
set_parameter_property OSC_CLOCK DEFAULT_VALUE 108000000
set_parameter_property OSC_CLOCK DISPLAY_NAME OSC_CLOCK
set_parameter_property OSC_CLOCK TYPE INTEGER
set_parameter_property OSC_CLOCK UNITS None
set_parameter_property OSC_CLOCK ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OSC_CLOCK HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 chipselect chipselect Input 1
add_interface_port s1 address address Input 3
add_interface_port s1 read read Input 1
add_interface_port s1 write write Input 1
add_interface_port s1 readdata readdata Output 32
add_interface_port s1 writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 54000000
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point ad1_clk
# 
add_interface ad1_clk conduit end
set_interface_property ad1_clk associatedClock ""
set_interface_property ad1_clk associatedReset ""
set_interface_property ad1_clk ENABLED true
set_interface_property ad1_clk EXPORT_OF ""
set_interface_property ad1_clk PORT_NAME_MAP ""
set_interface_property ad1_clk SVD_ADDRESS_GROUP ""

add_interface_port ad1_clk ad1_clk export Output 1


# 
# connection point ad2_clk
# 
add_interface ad2_clk conduit end
set_interface_property ad2_clk associatedClock ""
set_interface_property ad2_clk associatedReset reset
set_interface_property ad2_clk ENABLED true
set_interface_property ad2_clk EXPORT_OF ""
set_interface_property ad2_clk PORT_NAME_MAP ""
set_interface_property ad2_clk SVD_ADDRESS_GROUP ""

add_interface_port ad2_clk ad2_clk export Output 1


# 
# connection point dac1_clk
# 
add_interface dac1_clk conduit end
set_interface_property dac1_clk associatedClock ""
set_interface_property dac1_clk associatedReset ""
set_interface_property dac1_clk ENABLED true
set_interface_property dac1_clk EXPORT_OF ""
set_interface_property dac1_clk PORT_NAME_MAP ""
set_interface_property dac1_clk SVD_ADDRESS_GROUP ""

add_interface_port dac1_clk dac1_clk export Output 1


# 
# connection point dac2_clk
# 
add_interface dac2_clk conduit end
set_interface_property dac2_clk associatedClock ""
set_interface_property dac2_clk associatedReset ""
set_interface_property dac2_clk ENABLED true
set_interface_property dac2_clk EXPORT_OF ""
set_interface_property dac2_clk PORT_NAME_MAP ""
set_interface_property dac2_clk SVD_ADDRESS_GROUP ""

add_interface_port dac2_clk dac2_clk export Output 1


# 
# connection point dac3_clk
# 
add_interface dac3_clk conduit end
set_interface_property dac3_clk associatedClock ""
set_interface_property dac3_clk associatedReset ""
set_interface_property dac3_clk ENABLED true
set_interface_property dac3_clk EXPORT_OF ""
set_interface_property dac3_clk PORT_NAME_MAP ""
set_interface_property dac3_clk SVD_ADDRESS_GROUP ""

add_interface_port dac3_clk dac3_clk export Output 1


# 
# connection point dac4_clk
# 
add_interface dac4_clk conduit end
set_interface_property dac4_clk associatedClock ""
set_interface_property dac4_clk associatedReset ""
set_interface_property dac4_clk ENABLED true
set_interface_property dac4_clk EXPORT_OF ""
set_interface_property dac4_clk PORT_NAME_MAP ""
set_interface_property dac4_clk SVD_ADDRESS_GROUP ""

add_interface_port dac4_clk dac4_clk export Output 1


# 
# connection point light_clk
# 
add_interface light_clk conduit end
set_interface_property light_clk associatedClock clock_sink
set_interface_property light_clk associatedReset reset
set_interface_property light_clk ENABLED true
set_interface_property light_clk EXPORT_OF ""
set_interface_property light_clk PORT_NAME_MAP ""
set_interface_property light_clk SVD_ADDRESS_GROUP ""

add_interface_port light_clk light_clk export Output 1


# 
# connection point clk_source
# 
add_interface clk_source clock end
set_interface_property clk_source clockRate 108000000
set_interface_property clk_source ENABLED true
set_interface_property clk_source EXPORT_OF ""
set_interface_property clk_source PORT_NAME_MAP ""
set_interface_property clk_source SVD_ADDRESS_GROUP ""

add_interface_port clk_source clk_source clk Input 1

